(()=>{
if(window.__BZ_UI572__)return;window.__BZ_UI572__=1;
const $=s=>document.querySelector(s),storage=()=>document.getElementById('u572store');
const style=document.createElement('style');style.textContent=`
body{background:radial-gradient(circle at 50% -10%,rgba(97,111,255,.15),transparent 30%),#07111f!important}.hero-card{background:radial-gradient(circle at 100% 0,rgba(132,91,255,.23),transparent 38%),linear-gradient(145deg,#20365d,#10233d)!important}.premium-stats .stat-income{background:rgba(31,117,83,.19)!important}.premium-stats .stat-energy{background:rgba(178,118,35,.17)!important}.premium-stats .stat-xp{background:rgba(115,83,218,.18)!important}
#tab-home>:not(.hero-card):not(#u572menu){display:none!important}#u572store{display:none!important}#v53RaceOpen{display:none!important}
.u572-menu{display:block!important;margin:14px 0 24px;padding:14px;border:1px solid rgba(125,149,218,.18);border-radius:25px;background:radial-gradient(circle at 90% 0,rgba(111,82,230,.12),transparent 28%),linear-gradient(145deg,#12233b,#091725);box-shadow:0 18px 45px rgba(0,0,0,.18)}.u572-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.u572-head span{color:#8194b6;font-size:9px;font-weight:900;letter-spacing:1.4px}.u572-head h2{margin:3px 0 0;font-size:22px}.u572-now{padding:6px 8px;border-radius:999px;background:rgba(75,210,151,.1);color:#8ce5bd;font-size:9px}.u572-flow{display:flex;gap:5px;overflow:auto;margin:10px 0;padding:8px;border-radius:13px;background:rgba(0,0,0,.16);white-space:nowrap;scrollbar-width:none}.u572-flow::-webkit-scrollbar{display:none}.u572-flow b{font-size:9px;color:#c7d1e5}.u572-flow i{font-style:normal;color:#536b8a}
.u572-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.u572-card{position:relative;min-height:112px;padding:13px;border:1px solid rgba(255,255,255,.08);border-radius:19px;color:white;text-align:left;overflow:hidden;box-shadow:inset 0 1px 0 rgba(255,255,255,.035)}.u572-card:active{transform:scale(.985)}.u572-card b{display:block;font-size:29px}.u572-card strong{display:block;margin-top:6px;font-size:16px}.u572-card small{display:block;margin-top:4px;padding-right:36px;color:#c0cbe0;font-size:9.5px;line-height:1.35}.u572-card em{position:absolute;right:9px;bottom:9px;font-style:normal;font-size:8px;padding:5px 7px;border-radius:999px;background:rgba(0,0,0,.18)}.u572-deal{background:linear-gradient(145deg,#613826,#291b26)}.u572-biz{background:linear-gradient(145deg,#155150,#102d3e)}.u572-game{background:linear-gradient(145deg,#403783,#192441)}.u572-award{background:linear-gradient(145deg,#6a4f20,#30233b)}.u572-dev{grid-column:1/-1;min-height:96px;background:linear-gradient(120deg,#15516a,#2c347b)}
.u572-overlay{position:fixed;inset:0;z-index:12420;display:flex;align-items:flex-end;background:rgba(2,7,16,.82);backdrop-filter:blur(10px)}.u572-overlay.hidden{display:none}.u572-sheet{width:100%;height:min(93dvh,900px);display:flex;flex-direction:column;border-radius:27px 27px 0 0;background:linear-gradient(180deg,#10213a,#081522);overflow:hidden;border:1px solid rgba(118,143,207,.13)}.u572-top{height:72px;flex:0 0 72px;display:flex;align-items:center;justify-content:space-between;padding:0 15px;border-bottom:1px solid rgba(255,255,255,.07)}.u572-top span{font-size:8px;color:#8297ba;letter-spacing:1.4px;font-weight:900}.u572-top h2{margin:3px 0 0;font-size:22px}.u572-close{width:42px;height:42px;border-radius:13px;border:1px solid rgba(255,255,255,.09);background:#172941;color:white;font-size:25px}.u572-body{flex:1;overflow:auto;padding:13px 12px calc(28px + env(safe-area-inset-bottom));scroll-behavior:smooth}.u572-intro{margin-bottom:11px;padding:14px;border-radius:18px;background:linear-gradient(145deg,rgba(57,78,135,.36),rgba(14,28,48,.78));border:1px solid rgba(112,140,221,.14)}.u572-intro strong{font-size:16px}.u572-intro p{margin:4px 0 0;color:#92a3bd;font-size:10px;line-height:1.45}.u572-body>.section,.u572-body>[data-u572-home]{display:block!important;margin:0 0 11px!important}.u572-body .xp569-grid,.u572-body .xp570-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.u572-social{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:11px}.u572-social button{min-height:92px;padding:12px;border-radius:17px;border:1px solid rgba(255,255,255,.08);color:white;text-align:left}.u572-social button:first-child{background:linear-gradient(145deg,#5a3527,#28233a)}.u572-social button:last-child{background:linear-gradient(145deg,#244772,#262858)}.u572-social b{font-size:26px}.u572-social strong{display:block;margin-top:5px;font-size:13px}.u572-social small{display:block;margin-top:3px;font-size:8px;color:#a4b5d1}.u572-empty{padding:18px;text-align:center;color:#8191aa;font-size:11px;border:1px dashed rgba(130,150,200,.14);border-radius:16px}.mini-modal{z-index:12750!important}.v53-overlay{z-index:12760!important}.lp566-overlay{z-index:12770!important}.bottom-nav{background:rgba(8,18,32,.97)!important;border-top:1px solid rgba(113,138,200,.13)!important}.bottom-nav .nav-btn.active{background:linear-gradient(145deg,rgba(76,107,212,.25),rgba(104,75,201,.15))!important;border-radius:16px!important}
@media(max-width:390px){.u572-card{min-height:104px}.u572-body .xp569-grid,.u572-body .xp570-grid{grid-template-columns:1fr}}
`;document.head.appendChild(style);
function root(){let s=$('#u572store');if(!s){s=document.createElement('div');s.id='u572store';document.body.appendChild(s)}let o=$('#u572overlay');if(!o){o=document.createElement('div');o.id='u572overlay';o.className='u572-overlay hidden';o.innerHTML='<section class="u572-sheet"><header class="u572-top"><div><span id="u572kick">BUSINESS ZERO</span><h2 id="u572title">Раздел</h2></div><button class="u572-close">×</button></header><main id="u572body" class="u572-body"></main></section>';document.body.appendChild(o);o.querySelector('.u572-close').onclick=close}return{s,o,c:$('#u572body')}}
const sec=id=>document.getElementById(id)?.closest('.section');
const canonical=()=>[...new Set([$('.mini-game-section'),$('#xpTrainers569'),$('#xpTrainersExtra570'),sec('dailyQuests'),$('#loginSection'),sec('levelRewards'),sec('achievements'),sec('deals'),sec('businesses'),$('#v50Launch'),$('#v51CardsLaunch')].filter(Boolean))];
function isOldShortcut(n){const t=String(n?.innerText||n?.textContent||'').toLowerCase();return t.includes('сделки')&&t.includes('бизнес')&&(t.includes('xp-тренаж')||t.includes('опыт без энергии')||t.includes('заработок + xp'))}
function collectHome(){const {s,c}=root(),home=$('#tab-home');if(!home)return;[...home.children].forEach(n=>{if(n.classList.contains('hero-card')||n.id==='u572menu')return;n.dataset.u572='1';n.dataset.u572Home='1';if(!s.contains(n)&&!c.contains(n))s.appendChild(n)});canonical().forEach(n=>{n.dataset.u572='1';if(!s.contains(n)&&!c.contains(n))s.appendChild(n)});const party=$('#localParty566Card');if(party){party.dataset.u572='1';party.dataset.u572Party='1';if(!s.contains(party)&&!c.contains(party))s.appendChild(party)}}
function collectProfile(){const {s,c}=root();[$('#loginSection'),sec('levelRewards'),sec('achievements')].filter(Boolean).forEach(n=>{n.dataset.u572='1';if(!s.contains(n)&&!c.contains(n))s.appendChild(n)})}
function collect(){collectHome();collectProfile()}
function ready(){return document.querySelectorAll('.quest-btn.ready,[data-level-reward],.login-claim:not([disabled]),[data-achievement-claim]').length}
function refresh(){const cash=Number(state?.cash||0),lvl=Number(state?.level||1),n=$('#u572now');if(n)n.textContent=cash<3500?'Сейчас: сделка':lvl<5?'Сейчас: бизнес':'Сейчас: прокачка';const r=$('#u572rewards'),q=ready();if(r)r.textContent=q?`${q} забрать`:'всё собрано'}
function menu(){if($('#u572menu'))return;const home=$('#tab-home'),hero=home?.querySelector('.hero-card');if(!hero)return;const x=document.createElement('section');x.id='u572menu';x.className='u572-menu';x.innerHTML=`<div class="u572-head"><div><span>ГЛАВНОЕ МЕНЮ</span><h2>Всё нужное — здесь</h2></div><b id="u572now" class="u572-now">Выбери действие</b></div><div class="u572-flow"><b>1. Заработай</b><i>→</i><b>2. Развивай бизнес</b><i>→</i><b>3. Прокачивай XP</b><i>→</i><b>4. Забирай награды</b></div><div class="u572-grid"><button class="u572-card u572-deal" data-u572-open="deals"><b>💸</b><strong>Сделки</strong><small>Быстрый заработок, риск и XP</small><em>открыть</em></button><button class="u572-card u572-biz" data-u572-open="business"><b>🏢</b><strong>Бизнесы</strong><small>Покупка, улучшения и доход</small><em>открыть</em></button><button class="u572-card u572-game" data-u572-open="games"><b>🎮</b><strong>Прокачка</strong><small>Все игры и тренажёры в одном месте</small><em>все игры</em></button><button class="u572-card u572-award" data-u572-open="rewards"><b>🏆</b><strong>Достижения</strong><small>Задания, серии, уровни и награды</small><em id="u572rewards">всё собрано</em></button><button class="u572-card u572-dev" data-u572-open="develop"><b>◆</b><strong>Центр развития</strong><small>Сезон • миссии • биржа • коллекции • новые системы</small><em>открыть</em></button></div>`;hero.insertAdjacentElement('afterend',x);x.querySelectorAll('[data-u572-open]').forEach(b=>b.onclick=()=>open(b.dataset.u572Open))}
function intro(t,p){const x=document.createElement('div');x.className='u572-intro';x.innerHTML=`<strong>${t}</strong><p>${p}</p>`;return x}function add(c,n){if(n)c.appendChild(n)}
function developNodes(){const {s}=root();const excluded=new Set([$('.mini-game-section'),$('#xpTrainers569'),$('#xpTrainersExtra570'),sec('dailyQuests'),sec('deals'),sec('businesses')].filter(Boolean));return [...s.children].filter(n=>n.dataset.u572Home==='1'&&!excluded.has(n)&&!isOldShortcut(n))}
function open(type){collect();const {o,c}=root();c.innerHTML='';const title=$('#u572title'),kick=$('#u572kick');if(type==='deals'){kick.textContent='ЗАРАБОТОК';title.textContent='Сделки';c.appendChild(intro('💸 Быстрый заработок','Все сделки собраны здесь. Смотри уровень, энергию и риск.'));add(c,sec('deals'))}if(type==='business'){kick.textContent='ПАССИВНЫЙ ДОХОД';title.textContent='Бизнесы';c.appendChild(intro('🏢 Строй империю','Покупай и улучшай бизнесы. Доход начисляется автоматически.'));add(c,sec('businesses'))}if(type==='rewards'){kick.textContent='НАГРАДЫ И ПРОГРЕСС';title.textContent='Достижения';c.appendChild(intro('🏆 Всё, что можно выполнить и забрать','Ежедневные задания, серия входов, награды за уровни и достижения находятся здесь.'));add(c,sec('dailyQuests'));add(c,$('#loginSection'));add(c,sec('levelRewards'));add(c,sec('achievements'))}if(type==='games'){kick.textContent='ВСЕ ИГРЫ';title.textContent='Прокачка';c.appendChild(intro('🎮 Играй и прокачивайся','Денежный поток, 12 XP-тренажёров, Party Arena и гонки — в одном разделе.'));const s=document.createElement('div');s.className='u572-social';s.innerHTML='<button id="u572race"><b>🏎️</b><strong>Гонки с друзьями</strong><small>соревнование и комнаты</small></button><button id="u572party"><b>👥</b><strong>Party Arena</strong><small>1×1 или 2×2 на одном телефоне</small></button>';c.appendChild(s);s.querySelector('#u572race').onclick=()=>$('#v53RaceOpen')?.click();s.querySelector('#u572party').onclick=()=>$('#localParty566Card .lp566-open')?.click();add(c,$('.mini-game-section'));add(c,$('#xpTrainers569'));add(c,$('#xpTrainersExtra570'))}if(type==='develop'){kick.textContent='РАЗВИТИЕ';title.textContent='Центр развития';c.appendChild(intro('◆ Долгосрочное развитие','Сезон, миссии, биржа, коллекции и новые игровые системы собраны здесь.'));const ns=developNodes();if(ns.length)ns.forEach(n=>add(c,n));else c.appendChild(Object.assign(document.createElement('div'),{className:'u572-empty',textContent:'Разделы развития загружаются…'}))}o.classList.remove('hidden');document.body.style.overflow='hidden';c.scrollTop=0}
function close(){const {s,o,c}=root();[...c.children].forEach(n=>{if(n.dataset?.u572)s.appendChild(n)});o.classList.add('hidden');document.body.style.removeProperty('overflow')}
function install(){collect();menu();collect();refresh()}let tries=0,t=setInterval(()=>{tries++;try{install()}catch{}if(tries>40)clearInterval(t)},400);setInterval(()=>{try{collect();refresh()}catch{}},1800)
})();
