(()=>{
if(window.__BZ_UI572__)return;window.__BZ_UI572__=1;
const $=s=>document.querySelector(s),storage=()=>document.getElementById('u572store'),content=()=>document.getElementById('u572body');
const style=document.createElement('style');style.textContent=`
body{background:radial-gradient(circle at 50% -10%,rgba(97,111,255,.14),transparent 30%),#07111f!important}.hero-card{background:radial-gradient(circle at 100% 0,rgba(132,91,255,.22),transparent 38%),linear-gradient(145deg,#20365d,#10233d)!important}.premium-stats .stat-income{background:rgba(31,117,83,.19)!important}.premium-stats .stat-energy{background:rgba(178,118,35,.17)!important}.premium-stats .stat-xp{background:rgba(115,83,218,.18)!important}
.u572-menu{margin:14px 0;padding:14px;border:1px solid rgba(125,149,218,.16);border-radius:24px;background:linear-gradient(145deg,#12233b,#091725)}.u572-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.u572-head span{color:#8194b6;font-size:9px;font-weight:900;letter-spacing:1.4px}.u572-head h2{margin:3px 0 0;font-size:22px}.u572-now{padding:6px 8px;border-radius:999px;background:rgba(75,210,151,.1);color:#8ce5bd;font-size:9px}.u572-flow{display:flex;gap:5px;overflow:auto;margin:10px 0;padding:8px;border-radius:13px;background:rgba(0,0,0,.16);white-space:nowrap}.u572-flow b{font-size:9px;color:#c7d1e5}.u572-flow i{font-style:normal;color:#536b8a}
.u572-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.u572-card{position:relative;min-height:112px;padding:12px;border:1px solid rgba(255,255,255,.07);border-radius:18px;color:white;text-align:left;overflow:hidden}.u572-card b{display:block;font-size:27px}.u572-card strong{display:block;margin-top:6px;font-size:15px}.u572-card small{display:block;margin-top:4px;color:#b2c0d7;font-size:9px;line-height:1.3}.u572-card em{position:absolute;right:9px;bottom:9px;font-style:normal;font-size:8px;padding:5px 7px;border-radius:999px;background:rgba(0,0,0,.18)}.u572-deal{background:linear-gradient(145deg,#573524,#251b24)}.u572-biz{background:linear-gradient(145deg,#174a48,#102b3d)}.u572-game{background:linear-gradient(145deg,#3c3477,#18233f)}.u572-award{background:linear-gradient(145deg,#624a22,#292239)}.u572-dev{grid-column:1/-1;min-height:92px;background:linear-gradient(120deg,#16465b,#272b6d)}
#u572store{display:none!important}.u572-overlay{position:fixed;inset:0;z-index:12420;display:flex;align-items:flex-end;background:rgba(2,7,16,.8);backdrop-filter:blur(10px)}.u572-overlay.hidden{display:none}.u572-sheet{width:100%;height:min(93dvh,900px);display:flex;flex-direction:column;border-radius:27px 27px 0 0;background:linear-gradient(180deg,#10213a,#081522);overflow:hidden}.u572-top{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 15px;border-bottom:1px solid rgba(255,255,255,.07)}.u572-top span{font-size:8px;color:#8297ba;letter-spacing:1.4px;font-weight:900}.u572-top h2{margin:3px 0 0;font-size:22px}.u572-close{width:42px;height:42px;border-radius:13px;border:1px solid rgba(255,255,255,.09);background:#172941;color:white;font-size:25px}.u572-body{flex:1;overflow:auto;padding:13px 12px calc(26px + env(safe-area-inset-bottom))}.u572-intro{margin-bottom:11px;padding:13px;border-radius:18px;background:linear-gradient(145deg,rgba(57,78,135,.34),rgba(14,28,48,.75));border:1px solid rgba(112,140,221,.13)}.u572-intro strong{font-size:15px}.u572-intro p{margin:4px 0 0;color:#92a3bd;font-size:10px;line-height:1.4}.u572-body>.section,.u572-body>#localParty566Card{margin:0 0 11px!important}.u572-body .xp569-grid,.u572-body .xp570-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.u572-social{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px}.u572-social button{padding:11px;border-radius:16px;border:1px solid rgba(255,255,255,.07);background:#142941;color:white;text-align:left}.u572-social b{font-size:23px}.u572-social strong{display:block;margin-top:4px;font-size:12px}.u572-social small{font-size:8px;color:#8296b7}.mini-modal{z-index:12750!important}.v53-overlay{z-index:12760!important}.lp566-overlay{z-index:12770!important}.bottom-nav{background:rgba(8,18,32,.97)!important;border-top:1px solid rgba(113,138,200,.13)!important}.bottom-nav .nav-btn.active{background:linear-gradient(145deg,rgba(76,107,212,.25),rgba(104,75,201,.15))!important;border-radius:16px!important}
@media(max-width:390px){.u572-card{min-height:104px}.u572-body .xp569-grid,.u572-body .xp570-grid{grid-template-columns:1fr}}
`;document.head.appendChild(style);
function root(){let s=$('#u572store');if(!s){s=document.createElement('div');s.id='u572store';document.body.appendChild(s)}let o=$('#u572overlay');if(!o){o=document.createElement('div');o.id='u572overlay';o.className='u572-overlay hidden';o.innerHTML='<section class="u572-sheet"><header class="u572-top"><div><span id="u572kick">BUSINESS ZERO</span><h2 id="u572title">Раздел</h2></div><button class="u572-close">×</button></header><main id="u572body" class="u572-body"></main></section>';document.body.appendChild(o);o.querySelector('.u572-close').onclick=close}return{s,o,c:$('#u572body')}}
const sec=id=>document.getElementById(id)?.closest('.section');
function nodes(){return [...new Set([$('.mini-game-section'),$('#xpTrainers569'),$('#xpTrainersExtra570'),$('#localParty566Card'),sec('dailyQuests'),$('#loginSection'),sec('levelRewards'),sec('achievements'),sec('deals'),sec('businesses'),$('#v50Launch')].filter(Boolean))]}
function collect(){const {s,c}=root();for(const n of nodes()){n.dataset.u572='1';if(!s.contains(n)&&!c.contains(n))s.appendChild(n)}}
function ready(){return document.querySelectorAll('.quest-btn.ready,[data-level-reward],.login-claim:not([disabled])').length}
function refresh(){const c=Number(state?.cash||0),l=Number(state?.level||1),n=$('#u572now');if(n)n.textContent=c<3500?'Сейчас: сделка':l<5?'Сейчас: купи бизнес':'Сейчас: прокачка';const r=$('#u572rewards');if(r)r.textContent=ready()?`${ready()} забрать`:'всё собрано'}
function menu(){if($('#u572menu'))return;const home=$('#tab-home'),hero=home?.querySelector('.hero-card');if(!hero)return;const x=document.createElement('section');x.id='u572menu';x.className='u572-menu';x.innerHTML=`<div class="u572-head"><div><span>ГЛАВНОЕ МЕНЮ</span><h2>Что хочешь сделать?</h2></div><b id="u572now" class="u572-now">Выбери действие</b></div><div class="u572-flow"><b>1. Заработай</b><i>→</i><b>2. Купи бизнес</b><i>→</i><b>3. Прокачай XP</b><i>→</i><b>4. Забери награды</b></div><div class="u572-grid"><button class="u572-card u572-deal" data-u572="deals"><b>💸</b><strong>Сделки</strong><small>Быстрый заработок и риск</small><em>открыть</em></button><button class="u572-card u572-biz" data-u572="business"><b>🏢</b><strong>Бизнесы</strong><small>Доход и улучшения</small><em>открыть</em></button><button class="u572-card u572-game" data-u572="games"><b>🎮</b><strong>Прокачка</strong><small>Все игры и XP в одном месте</small><em>12+ игр</em></button><button class="u572-card u572-award" data-u572="rewards"><b>🏆</b><strong>Достижения</strong><small>Задания, уровни, награды</small><em id="u572rewards">всё собрано</em></button><button class="u572-card u572-dev" data-u572="develop"><b>◆</b><strong>Центр развития</strong><small>Сезон • миссии • биржа • коллекции</small><em>открыть</em></button></div>`;hero.insertAdjacentElement('afterend',x);x.querySelectorAll('[data-u572]').forEach(b=>b.onclick=()=>open(b.dataset.u572))}
function intro(t,p){const x=document.createElement('div');x.className='u572-intro';x.innerHTML=`<strong>${t}</strong><p>${p}</p>`;return x}function add(c,n){if(n)c.appendChild(n)}
function open(type){collect();if(type==='develop'){($('#v50Launch')?.querySelector('[data-v50-open="season"]')||$('#v50Launch')?.querySelector('[data-v50-open]'))?.click();return}const {o,c}=root();c.innerHTML='';const title=$('#u572title'),kick=$('#u572kick');if(type==='deals'){kick.textContent='ЗАРАБОТОК';title.textContent='Сделки';c.appendChild(intro('💸 Быстрый заработок','Выбирай сделку по уровню, энергии и риску.'));add(c,sec('deals'))}if(type==='business'){kick.textContent='ПАССИВНЫЙ ДОХОД';title.textContent='Бизнесы';c.appendChild(intro('🏢 Строй империю','Покупай и улучшай бизнесы, чтобы увеличивать пассивный доход.'));add(c,sec('businesses'))}if(type==='rewards'){kick.textContent='ПРОГРЕСС';title.textContent='Достижения';c.appendChild(intro('🏆 Всё в одном месте','Ежедневные задания, серия входов, награды за уровни и достижения.'));add(c,sec('dailyQuests'));add(c,$('#loginSection'));add(c,sec('levelRewards'));add(c,sec('achievements'))}if(type==='games'){kick.textContent='ВСЕ ИГРЫ';title.textContent='Прокачка';c.appendChild(intro('🎮 Играй и прокачивайся','Все XP-тренажёры, аркады и игры с друзьями теперь здесь.'));const s=document.createElement('div');s.className='u572-social';s.innerHTML='<button id="u572race"><b>🏎️</b><strong>Гонки</strong><small>с друзьями</small></button><button id="u572party"><b>👥</b><strong>Party Arena</strong><small>на одном телефоне</small></button>';c.appendChild(s);s.querySelector('#u572race').onclick=()=>$('#v53RaceOpen')?.click();s.querySelector('#u572party').onclick=()=>$('#localParty566Card .lp566-open')?.click();add(c,$('.mini-game-section'));add(c,$('#xpTrainers569'));add(c,$('#xpTrainersExtra570'));add(c,$('#localParty566Card'))}o.classList.remove('hidden');document.body.style.overflow='hidden';c.scrollTop=0}
function close(){const {s,o,c}=root();[...c.children].forEach(n=>{if(n.dataset?.u572)s.appendChild(n)});o.classList.add('hidden');document.body.style.removeProperty('overflow')}
function install(){collect();menu();refresh()}let i=0,q=setInterval(()=>{i++;try{install()}catch(e){}if(i>30)clearInterval(q)},500);setInterval(()=>{try{collect();refresh()}catch{}},2200)
})();
